language: java
jdk:
- oraclejdk8
deploy:
  provider: cloudfoundry
  username: 369558172@qq.com
  password:
    secure: "ey9l5jrvsqy2nPT1BuMq/EKqsCbyfRq2YKoj2VY25vEozAfj35juxQ0N3OgQNL1751VfJ9FdNYTgNA8qPKRMlEXD
            +eGeFUcaEwcG2pMkJt6iu4YQAm/ivbERkC+5uQWvyy08L6YkRgbeVZCD7iY5MWV6KDpo1bKL3MLn7DNYqgL5d6lF0/xrn68sswA
            y06+6o1ZJsqkCaSpdz3xx2PLD9qj8ymSe+gYHY5ZDZ2OtZSOrKZEBLu6k/+smcE8ns1ejMkgeP+zF8S0Xc254f7qnmL6SnIK/sM
            tfKwrLRsqdmUORMZb70aFR5RdGgKKOQ1NlRppol33tVnE/cdC6QLPoVImJteNKH3MFL4IGRQVkduo3kyW+30Pu44W+qsciI6jqS
            muwDxgSAqiLY7ydxSZNkgUOJBdpNsCO6lyFNe6aP8y2xJ/2xwYiWLrdobA+uPw0UL3fL6rOpbm8gqx4nYcUMZhb4MRvmqdNdE3a
            SVEoc9vj6Ly8te/BgCyLJlLkvISXsMWJj9/YiUeh3UBukxguHG03jEJKWutYnBfFUWLhI5yvhMVnait0d8GC8OBB1aHUFj5bcge
            pkxY4ZnpDB9Tor/QSgFC6U0Hfpvf7r0do8DRX68VKOaQ8aakedR8b1fovaJgQYO+Cbl9ye7FDp7A8KUG/vdsrzt3/KAMVQltkx1
            A="
  api: https://api.run.pivotal.io
  organization: morenbuou3
  space: development
  app: shop
  on:
    repo: morenbuou3/Shop
    branch: master