language: java
jdk:
- oraclejdk8
deploy:
  provider: cloudfoundry
  api: https://api.run.pivotal.io
  username: 369558172@qq.com
  password:
    secure: Fr7BUNmSbfRsJMYu8k2D7ZrEIDbEx95x1wHPnsMe9JCb21MTb//O396VsmKxzBc4ZB042uo0hWfN9xfdEYe7bMZo9IZIkGs59TaxUDDnUQETTXPgITA/5G2DlO3ghmgch58/6DwNyPl1IZn1m3oVl9KLAVTT4feqmPmoJh0WI/FlLtY6mKlSnfQF7mdOYQtkLn5YhaQ2MVEQu5GTKXkjP95ai7Urmt9V5+4ikMiWQKUSKB4Y7qVNH/kSzdoRR6zpmRJLVkBhTgRvmK8XJnEkAacBtHcrH8CJuy7PbD3+hpbDjNoQaR1RN0sWUppxjQ/Nd+AnskQPiQVETVHDuduyRkp0DiBrQujQ2nIH85UJQm7kuZYwNLlkt79MZ0AQUextRLuvBTw0YptQR+x0+0qEFmzO3HFKBXho8ZYubJQFxT9C4vJR39oI/2mzIvrboHeMrI8ZMhRQP6dxp9eOi7XaAJXRx6CLZX+UldJNzK3wTjwsmFSV3ioOAGRaP4K4wwKrroqunjJ3gq1CXlUoB6rmC6a8zmCzZ59PEaX1T18My/uHXaSrrpbsawG7vab80xSOlAvWJIdEXR1NvfxOLuuS1j6CEuvGdUlCWmxob4cS9hi/QFJa7f0FuOv3qqFBMHu/I4aaqPeg05AFxjl6ER17XGl1l3ctQ+JH85j9F3cDUqk=
  organization: morenbuou3
  space: development
  on:
    repo: morenbuou3/Shop
